      - name: Keep CCTV only
        run: |
          python3 << 'EOF'
          with open("source.m3u", "r", encoding="utf-8", errors="ignore") as f:
              lines = f.readlines()

          out = []

          for i, line in enumerate(lines):
              if line.startswith("#EXTM3U"):
                  out.append(line)

              elif line.startswith("#EXTINF") and "CCTV" in line:
                  out.append(line)

                  if i + 1 < len(lines):
                      out.append(lines[i + 1])

          with open("iptv.m3u", "w", encoding="utf-8") as f:
              f.writelines(out)
          EOF
